### ISSUE TITLE
新闻详情无法用self.navigationController pushVIewController

### ISSUE THREAD

**Issue by kiradea** [kiradea/NUIDay7-01-WangYiNewspaper#1]
新闻详情无法用self.navigationController pushVIewController
因为self.navigationController 为nil

**Comment by HUMiooo** [comment]
LJNews *news = self.newsList[indexPath.row];
    LJNewsDetailController *detail = [[LJNewsDetailController alloc]initWithurlString:news.url];
    [self presentViewController:detail animated:YES completion:nil];
???可否

**Comment by kiradea** [comment]
@zianazan 这样的确可以，但是为什么无法使用self.navigationController 呢？

**Comment by HUMiooo** [comment]
因为你没有创建navigationController 所以没法用啊，只有创建了才能啊，
https://www.jianshu.com/p/ef1cd11a4b53
可以看下navigationController的分析，不然不好理解

**Comment by kiradea** [comment]
@zianazan 
简单来说导航视图包含A视图，A视图包含B视图（UICollectionView），B视图中的UICollectionViewCell 通过    [self.contentView addSubview:self.newsController.view];包含了newscontroller，
问题为什么newscontroller方法中使用self.navigationController 是空？

**Comment by HUMiooo** [comment]
因为你根本就没有初始化navigationController啊，没有的话自然是空啊

**Comment by kiradea** [comment]
@HUMiooo  可是我在storyboard里面嵌入了navigationController

**Comment by HUMiooo** [comment]
storyboard 。。我不咋用，这里我没啥办法了，代码写的感觉好处理些

**Comment by iblocker** [comment]
打印一下self.navigationController，如果是空的，就需要去找到这个根视图的navigationController

**Comment by kiradea** [comment]
我打印过，是空的，你可以看一下上面的的回复！
